<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'DashboardController@index');
Route::post('/dashboard-sales-info/search', 'DashboardController@salesInfoSearchData');


// 排他制御
Route::post('/common/lock', 'CommonController@lock');
Route::post('/common/is-locked', 'CommonController@isLocked');
Route::post('/common/gain-lock', 'CommonController@gainLock');
Route::post('/common/release-lock', 'CommonController@releaseLock');
// グリッドで商品選択
Route::post('/common/get-product-info', 'CommonController@getProductInfo');
Route::post('/common/get-product-unit-price-list', 'CommonController@getProductUnitPriceList');
// 商品マスタのオートコンプリート
Route::post('/common/get-product-code-combo-list', 'CommonController@getProductCodeComboList');
Route::post('/common/get-product-code-combo-list-include-auto-flg', 'CommonController@getProductCodeComboListIncludeAutoFlg');
Route::post('/common/get-product-code-combo-list-all', 'CommonController@getProductCodeComboListAll');
Route::post('/common/get-product-name-combo-list', 'CommonController@getProductNameComboList');
Route::post('/common/get-product-name-combo-list-include-auto-flg', 'CommonController@getProductNameComboListludeAutoFlg');

// QR関連
Route::get('/smapri-success', 'SmapriController@success');
Route::get('/smapri-failed', 'SmapriController@failed');

// 担当者一覧
Route::get('/staff-list', 'Auth\StaffListController@index');
Route::post('/staff-list/search', 'Auth\StaffListController@searchData');
// 担当者編集
Route::get('/staff-edit/new', 'Auth\StaffEditController@index');
Route::get('/staff-edit/{id}', 'Auth\StaffEditController@index');
Route::post('/staff-edit/save', 'Auth\StaffEditController@save');
Route::post('/staff-edit/delete', 'Auth\StaffEditController@delete');
Route::post('/staff-edit/search', 'Auth\StaffEditController@searchData');
Route::post('/staff-edit/uploader', 'Auth\StaffEditController@uploader');

// ログイン
Route::get('/login', 'Auth\LoginController@index')->name('login');
Route::post('/login/check', 'Auth\LoginController@loginCheck');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

// 拠点一覧
Route::get('/base-list', 'BaseListController@index');
Route::post('/base-list/search', 'BaseListController@searchData');
// 拠点編集
Route::get('/base-edit/new', 'BaseEditController@index');
Route::get('/base-edit/{id}', 'BaseEditController@index');
Route::post('/base-edit/save', 'BaseEditController@save');
Route::post('/base-edit/delete', 'BaseEditController@delete');
// 倉庫一覧
Route::get('/warehouse-list', 'WarehouseListController@index');
Route::post('/warehouse-list/search', 'WarehouseListController@searchData');
// 倉庫編集
Route::get('/warehouse-edit/new', 'WarehouseEditController@index');
Route::get('/warehouse-edit/{id}', 'WarehouseEditController@index');
Route::post('/warehouse-edit/save', 'WarehouseEditController@save');
Route::post('/warehouse-edit/delete', 'WarehouseEditController@delete');
// 得意先一覧
Route::get('/new-customer-list', 'NewCustomerListController@index');
Route::post('/new-customer-list/search', 'NewCustomerListController@searchData');
// 得意先編集
Route::get('/new-customer-edit/new', 'NewCustomerEditController@index');
Route::get('/new-customer-edit/{id}', 'NewCustomerEditController@index');
Route::post('/new-customer-edit/save', 'NewCustomerEditController@save');
Route::post('/new-customer-edit/delete', 'NewCustomerEditController@delete');
Route::post('/new-customer-edit/activate', 'NewCustomerEditController@activate');
// 得意先担当者設定
Route::get('/customer-staff', 'CustomerStaffController@index');
Route::post('/customer-staff/search', 'CustomerStaffController@searchData');
Route::post('/customer-staff/searchCustomer', 'CustomerStaffController@searchCustomer');
Route::post('/customer-staff/save', 'CustomerStaffController@save');
Route::post('/customer-staff/delete', 'CustomerStaffController@delete');
Route::post('/customer-staff/approval', 'CustomerStaffController@approval');
Route::post('/customer-staff/rejection', 'CustomerStaffController@rejection');
// 見積依頼入力・見積依頼詳細
Route::get('/quote-request-edit/new', 'QuoteRequestController@index');
Route::get('/quote-request-edit/download/default/{cutomerid}/{fileName}', 'QuoteRequestController@downloadDefault');
Route::get('/quote-request-edit/exists/{id}/{fileName}', 'QuoteRequestController@existsFile');
Route::get('/quote-request-edit/download/{id}/{fileName}', 'QuoteRequestController@download');
Route::get('/quote-request-edit/{id}', 'QuoteRequestController@index');
Route::post('/quote-request-edit/get-matter', 'QuoteRequestController@getMatter');
Route::post('/quote-request-edit/save', 'QuoteRequestController@save');
Route::post('/quote-request-edit/save-draft', 'QuoteRequestController@saveDraft');
Route::post('/quote-request-edit/save-default', 'QuoteRequestController@saveDefault');
Route::post('/quote-request-edit/delete-request-kbn', 'QuoteRequestController@deleteRequestKbn');
Route::post('/quote-request-edit/delete-request', 'QuoteRequestController@deleteRequest');
Route::post('/quote-request-edit/get-template-data', 'QuoteRequestController@getTemplateData');
// 見積依頼一覧
Route::get('/quote-request-list', 'QuoteRequestListController@index');
Route::post('/quote-request-list/search', 'QuoteRequestListController@searchData');
// 見積登録
Route::get('/quote-edit/new', 'QuoteEditController@index');
Route::get('/quote-edit/{matterId}', 'QuoteEditController@index');
Route::get('/quote-edit/exists/{id}/{filename}', 'QuoteEditController@existsFile');
Route::get('/quote-edit/download/{id}/{filename}', 'QuoteEditController@download');
Route::post('/quote-edit/confirm-matter', 'QuoteEditController@confirmMatter');
Route::post('/quote-edit/confirm-quote', 'QuoteEditController@confirmQuote');
Route::post('/quote-edit/search-quote', 'QuoteEditController@searchQuote');
Route::post('/quote-edit/save', 'QuoteEditController@save');
Route::post('/quote-edit/save-zero', 'QuoteEditController@saveZero');
Route::post('/quote-edit/apply', 'QuoteEditController@apply');
Route::post('/quote-edit/apply-cancel', 'QuoteEditController@applyCancel');
Route::post('/quote-edit/complete-estimation', 'QuoteEditController@completeEstimation');
Route::post('/quote-edit/received-order', 'QuoteEditController@receivedOrder');
Route::post('/quote-edit/cancel-received-order', 'QuoteEditController@cancelReceivedOrder');
Route::post('/quote-edit/delete', 'QuoteEditController@delete');
Route::post('/quote-edit/export-csv', 'QuoteEditController@exportCSV');
Route::post('/quote-edit/print-target', 'QuoteEditController@printTarget');
Route::post('/quote-edit/get-products-info', 'QuoteEditController@getProductsInfo');
// 見積一覧
Route::get('/quote-list', 'QuoteListController@index');
Route::post('/quote-list/search', 'QuoteListController@searchData');
Route::post('/quote-list/approval/judge', 'QuoteListController@judge');

// 見積書
Route::get('/quote-report/print/{id}', 'QuoteReportController@print');
Route::get('/quote-report/print-target/{id}', 'QuoteReportController@printTarget');
Route::post('/quote-report/save', 'QuoteReportController@save');

// 受発注一覧
Route::get('/order-list', 'OrderListController@index');
Route::post('/order-list/search', 'OrderListController@searchData');
Route::post('/order-list/get-report-data', 'OrderListController@getReportData');
Route::post('/order-list/upload-pdf', 'OrderListController@uploadPdf');

// 発注登録
Route::get('/order-edit/{id}', 'OrderEditController@index');
Route::post('/order-edit/get-delivery-address-list', 'OrderEditController@getDeliveryAddressList');
Route::post('/order-edit/get-matter-info', 'OrderEditController@getMatterInfo');
Route::post('/order-edit/save', 'OrderEditController@save');
Route::post('/order-edit/application', 'OrderEditController@application');
Route::post('/order-edit/create-order-no', 'OrderEditController@createOrderNo');
Route::get('/order-edit/exists/{id}/{filename}', 'OrderEditController@existsFile');
Route::get('/order-edit/download/{id}/{fileName}', 'OrderEditController@download');

// いきなり発注
Route::get('/order-sudden', 'OrderSuddenController@index')->name('order.sudden');
Route::get('/order-sudden-ownstock', 'OrderSuddenController@index')->name('order.sudden.ownstock');
Route::post('/order-sudden/confirm-matter', 'OrderSuddenController@confirmMatter');
Route::post('/order-sudden/get-delivery-address-list', 'OrderSuddenController@getDeliveryAddressList');
Route::post('/order-sudden/save', 'OrderSuddenController@save');
Route::post('/order-sudden/application', 'OrderSuddenController@application');

// 発注明細
Route::get('/order-detail/{id}', 'OrderDetailController@index');
Route::post('/order-detail/save', 'OrderDetailController@save');
Route::post('/order-detail/csv-to-array', 'OrderDetailController@csvToArray');
Route::get('/order-detail/exists/{matterId}/{orderId}/{fileName}', 'OrderDetailController@existsFile');
Route::get('/order-detail/download/{matterId}/{orderId}/{fileName}', 'OrderDetailController@download');
Route::post('/order-detail/matter-address/get', 'OrderDetailController@getMatterAddress');
Route::post('/order-detail/received-order/search', 'OrderDetailController@searchReceivedOrder');
// 発注書
Route::get('/order-report/print/{id}', 'OrderReportController@print');

// 入荷一覧
Route::get('/arrival-list', 'ArrivalListController@index');
Route::post('/arrival-list/search', 'ArrivalListController@searchData');
Route::post('/arrival-list/exportExcel', 'ArrivalListController@exportExcel');
Route::post('/arrival-list/cancel', 'ArrivalListController@cancel');

// 案件一覧
Route::get('/matter-list', 'MatterListController@index');
Route::post('/matter-list/download', 'MatterListController@download');
Route::post('/matter-list/search', 'MatterListController@searchData');

// 案件登録
Route::get('/matter-edit/new', 'MatterEditController@index');
Route::get('/matter-edit/{id}', 'MatterEditController@index');
Route::post('/matter-edit/save', 'MatterEditController@save');

// 案件詳細
Route::get('/matter-detail/{id}', 'MatterDetailController@index');
Route::post('/matter-detail/get/index-gantt', 'MatterDetailController@getIndexGantt');
Route::post('/matter-detail/init/gantt', 'MatterDetailController@initGanttData');
Route::post('/matter-detail/get/scheduler', 'MatterDetailController@getSchedulerData');
Route::post('/matter-detail/save', 'MatterDetailController@save');
Route::post('/matter-detail/save/customer-standard', 'MatterDetailController@saveCustomerStandard');
Route::post('/matter-detail/get/chart', 'MatterDetailController@getChartData');
Route::post('/matter-detail/delete', 'MatterDetailController@delete');
Route::post('/matter-detail/complete', 'MatterDetailController@complete');
Route::post('/matter-detail/cancel-complete', 'MatterDetailController@cancelComplete');
Route::get('/matter-detail/exists/quote/{quoteVerId}/{filename}', 'MatterDetailController@existsQuoteFile');
Route::get('/matter-detail/exists/order/{matterId}/{orderId}/{filename}', 'MatterDetailController@existsOrderFile');
Route::get('/matter-detail/download/quote/{quoteVerId}/{filename}', 'MatterDetailController@downloadQuoteFile');
Route::get('/matter-detail/download/order/{matterId}/{orderId}/{filename}', 'MatterDetailController@downloadOrderFile');
Route::post('/matter-detail/matter-address/get', 'MatterDetailController@getMatterAddress');

// 通知
Route::get('/notice/read/{id}', 'NoticeController@ReadNotice');
Route::get('/notice/readAll', 'NoticeController@ReadAllNotices');
Route::get('/notice/readAllByNoticeflag/{notice_flg}', 'NoticeController@ReadAllNoticesByNoticeflag');
Route::get('/notice/getNoticesByNoticeflag/{notice_flg}', 'NoticeController@getNoticesByNoticeflag');

// 入荷検索
Route::get('/arrival-search', 'ArrivalSearchController@index');
Route::post('/arrival-search/search', 'ArrivalSearchController@searchData');
// 入荷検索結果
Route::get('/arrival-result', 'ArrivalResultController@index');
Route::post('/arrival-result/search', 'ArrivalResultController@searchData');
// 入荷処理
Route::get('/arrival-process', 'ArrivalProcessController@index');
Route::post('/arrival-process/search', 'ArrivalProcessController@searchData');
Route::post('/arrival-process/save', 'ArrivalProcessController@save');
Route::post('/arrival-process/print', 'ArrivalProcessController@print');
Route::post('/arrival-process/reprint', 'ArrivalProcessController@rePrint');
// 住所入力
Route::get('/address-edit/{id}', 'AddressEditController@index');
Route::post('/address-edit/save', 'AddressEditController@save');
// 出荷検索
Route::get('/shipping-search', 'ShippingSearchController@index');
// 出荷一覧
Route::get('/shipping-list', 'ShippingListController@index');
Route::post('/shipping-list/search', 'ShippingListController@searchData');
Route::get('/shipping-process', 'ShippingProcessController@index');
Route::post('/shipping-process/search', 'ShippingProcessController@searchData');
Route::post('/shipping-process/quantity', 'ShippingProcessController@quantity');
Route::post('/shipping-process/save', 'ShippingProcessController@save');
Route::get('/shipping-truck', 'ShippingTruckController@index');
Route::post('/shipping-truck/search', 'ShippingTruckController@searchData');
Route::post('/shipping-truck/save', 'ShippingTruckController@save');
// 出荷納品一覧
Route::get('/shipping-delivery-list', 'ShippingDeliveryListController@index');
Route::post('/shipping-delivery-list/search', 'ShippingDeliveryListController@searchData');
Route::post('/shipping-delivery-list/delete', 'ShippingDeliveryListController@delete');
Route::get('/shipping-delivery-list/show/{id}', 'ShippingDeliveryListController@show');
Route::post('/shipping-delivery-list/print', 'ShippingDeliveryListController@print');
Route::post('/shipping-delivery-list/exportExcel', 'ShippingDeliveryListController@exportExcel');
// 出荷指示
Route::get('/shipping-instruction/new', 'ShippingInstructionController@index');
Route::post('/shipping-instruction/search', 'ShippingInstructionController@searchData');
Route::get('/shipping-instruction/{shipmentId}', 'ShippingInstructionController@index');
Route::post('/shipping-instruction/save', 'ShippingInstructionController@save');
Route::post('/shipping-instruction/delivery', 'ShippingInstructionController@delivery');
// 納品
Route::get('/delivery-list', 'DeliveryListController@index');
Route::post('/delivery-list/search', 'DeliveryListController@searchData');
Route::get('/delivery-process', 'DeliveryProcessController@index');
Route::post('/delivery-process/search', 'DeliveryProcessController@searchData');
Route::post('/delivery-process/quantity', 'DeliveryProcessController@quantity');
Route::post('/delivery-process/save', 'DeliveryProcessController@save');
Route::get('/delivery-photo', 'DeliveryPhotoController@index');
Route::post('/delivery-photo/save', 'DeliveryPhotoController@save');
Route::get('/delivery-sign', 'DeliverySignController@index');
Route::post('/delivery-sign/save', 'DeliverySignController@save');
Route::post('/delivery-sign/print', 'DeliverySignController@print');
// 商品一覧
Route::get('/product-list', 'ProductListController@index');
Route::post('/product-list/search', 'ProductListController@searchData');
// 商品編集
Route::get('/product-edit/new', 'ProductEditController@index');
Route::get('/product-edit/{id}', 'ProductEditController@index');
Route::post('/product-edit/save', 'ProductEditController@save');
Route::post('/product-edit/delete', 'ProductEditController@delete');
Route::get('/product-nickname/{id}', 'ProductNicknameController@index');
Route::post('/product-nickname/save', 'ProductNicknameController@save');
Route::post('/product-nickname/delete', 'ProductNicknameController@delete');
Route::get('/product-campaign-price/{id}', 'ProductCampaignPriceController@index');
Route::post('/product-campaign-price/save', 'ProductCampaignPriceController@save');
Route::post('/product-campaign-price/delete', 'ProductCampaignPriceController@delete');
// 商品CSV取込
Route::get('/product-import', 'ProductImportController@index');
Route::post('/product-import/import', 'ProductImportController@import');
// 商品マスタチェック
Route::get('/product-check', 'ProductCheckController@index');
Route::post('/product-check/search', 'ProductCheckController@searchData');
Route::post('/product-check/select', 'ProductCheckController@selectedProduct');
Route::post('/product-check/getInfo', 'ProductCheckController@getInfo');
Route::post('/product-check/save', 'ProductCheckController@save');
Route::post('/product-check/lock', 'ProductCheckController@lock');
Route::post('/product-check/gainLock', 'ProductCheckController@gainLock');
// 在庫転換
Route::get('/stock-conversion', 'StockConversionController@index');
Route::post('/stock-conversion/search', 'StockConversionController@searchData');
Route::post('/stock-conversion/save', 'StockConversionController@save');
// 在庫照会(PC)
Route::get('/stock-search', 'StockSearchController@index');
Route::post('/stock-search/search', 'StockSearchController@searchData');
Route::post('/stock-search/print', 'StockSearchController@print');
// 在庫照会(スマホ)
Route::get('/stock-inquiry', 'StockInquiryController@index');
Route::post('/stock-inquiry/search', 'StockInquiryController@searchData');
Route::post('/stock-inquiry/detail', 'StockInquiryController@getDetail');
Route::post('/stock-inquiry/print', 'StockInquiryController@print');
// QR分割
Route::get('/qr-split', 'QrSplitController@index');
Route::post('/qr-split/search', 'QrSplitController@searchData');
Route::get('/qr-split-single-product', 'QrSplitSingleProductController@index');
Route::post('/qr-split-single-product/search', 'QrSplitSingleProductController@searchData');
Route::post('/qr-split-single-product/save', 'QrSplitSingleProductController@save');
Route::post('/qr-split-single-product/print', 'QrSplitSingleProductController@print');
Route::get('/qr-split-product-split', 'QrSplitProductSplitController@index');
Route::post('/qr-split-product-split/search', 'QrSplitProductSplitController@searchData');
Route::post('/qr-split-product-split/save', 'QrSplitProductSplitController@save');
Route::post('/qr-split-product-split/print', 'QrSplitProductSplitController@print');
Route::get('/qr-split-quantity-designation', 'QrSplitQuantityDesignationController@index');
Route::post('/qr-split-quantity-designation/save', 'QrSplitQuantityDesignationController@save');
Route::post('/qr-split-quantity-designation/print', 'QrSplitQuantityDesignationController@print');
// QR統合
Route::get('/qr-integration', 'QrIntegrationController@index');
Route::post('/qr-integration/save', 'QrIntegrationController@save');
Route::post('/qr-integration/print', 'QrIntegrationController@print');
// QR案件変更
Route::get('/qr-matter-change', 'QrMatterChangeController@index');
Route::post('/qr-matter-change/save', 'QrMatterChangeController@save');
// スマホ用メニュー
Route::get('/mobile-menu', 'MobileMenuController@index');
Route::post('/mobile-menu/save', 'MobileMenuController@save');
// 部門一覧
Route::get('/department-list', 'DepartmentListController@index');
Route::post('/department-list/search', 'DepartmentListController@searchData');
// 部門編集
Route::get('/department-edit/new', 'DepartmentEditController@index');
Route::get('/department-edit/{id}', 'DepartmentEditController@index');
Route::post('/department-edit/save', 'DepartmentEditController@save');
Route::post('/department-edit/delete', 'DepartmentEditController@delete');
// 仕入先／メーカー一覧
Route::get('/supplier-list', 'SupplierListController@index');
Route::post('/supplier-list/search', 'SupplierListController@searchData');
// 仕入先／メーカー編集
Route::get('/supplier-edit/new', 'SupplierEditController@index');
Route::get('/supplier-edit/{id}', 'SupplierEditController@index');
Route::post('/supplier-edit/save', 'SupplierEditController@save');
Route::post('/supplier-edit/delete', 'SupplierEditController@delete');
// 仕入先／メーカー対照マスタ
Route::get('/supplier-maker-contrast/new', 'SupplierMakerContrastController@index');
Route::get('/supplier-maker-contrast/{id}', 'SupplierMakerContrastController@index');
Route::post('/supplier-maker-contrast/search', 'SupplierMakerContrastController@searchData');
Route::post('/supplier-maker-contrast/save', 'SupplierMakerContrastController@save');
Route::post('/supplier-maker-contrast/delete', 'SupplierMakerContrastController@delete');
// 仕入先／メーカー価格ファイルマスタ
Route::get('/supplier-file/{id}', 'SupplierFileController@index');
Route::post('/supplier-file/save', 'SupplierFileController@save');
Route::post('/supplier-file/delete', 'SupplierFileController@delete');
Route::get('/supplier-file/openFile/{supplier_file_id}', 'SupplierFileController@openFile');
// 仕入詳細
Route::get('/purchase-detail', 'PurchaseDetailController@index');
Route::post('/purchase-detail/search', 'PurchaseDetailController@searchData');
Route::post('/purchase-detail/selectSupplier', 'PurchaseDetailController@selectSupplier');
Route::post('/purchase-detail/save', 'PurchaseDetailController@save');
Route::post('/purchase-detail/cancel', 'PurchaseDetailController@cancel');
Route::post('/purchase-detail/delete', 'PurchaseDetailController@delete');
// 支払予定一覧
Route::get('/payment-list', 'PaymentListController@index');
Route::post('/payment-list/search', 'PaymentListController@searchData');
Route::post('/payment-list/rebateInfo', 'PaymentListController@searchRebateData');
Route::post('/payment-list/billsInfo', 'PaymentListController@searchBillsData');
Route::post('/payment-list/save', 'PaymentListController@save');
Route::post('/payment-list/saveRebate', 'PaymentListController@saveRebate');
Route::post('/payment-list/saveBills', 'PaymentListController@saveBills');
Route::post('/payment-list/paymentRequest', 'PaymentListController@paymentRequest');
Route::post('/payment-list/cancelRequest', 'PaymentListController@cancelRequest');
Route::post('/payment-list/searchRequest', 'PaymentListController@searchRequest');
Route::post('/payment-list/approval', 'PaymentListController@approval');
Route::post('/payment-list/cancel', 'PaymentListController@cancel');
Route::post('/payment-list/closing', 'PaymentListController@closing');
Route::post('/payment-list/searchBranch', 'PaymentListController@searchBranch');
Route::get('/payment-list/download/{id}/{filename}', 'PaymentListController@download');

// 選択肢一覧
Route::get('/choice-list', 'ChoiceListController@index');
Route::post('/choice-list/search', 'ChoiceListController@searchData');
// 選択肢編集
Route::get('/choice-edit/new', 'ChoiceEditController@index');
Route::get('/choice-edit/{id}', 'ChoiceEditController@index');
Route::post('/choice-edit/save', 'ChoiceEditController@save');
Route::post('/choice-edit/delete', 'ChoiceEditController@delete');
// 項目一覧
Route::get('/item-list', 'ItemListController@index');
Route::post('/item-list/search', 'ItemListController@searchData');
// 項目編集
Route::get('/item-edit/new', 'ItemEditController@index');
Route::get('/item-edit/{id}', 'ItemEditController@index');
Route::post('/item-edit/save', 'ItemEditController@save');
Route::post('/item-edit/delete', 'ItemEditController@delete');
// 仕様項目一覧
Route::get('/spec-item-list', 'SpecItemListController@index');
Route::post('/spec-item-list/search', 'SpecItemListController@searchData');
// 仕様項目編集
Route::get('/spec-item-edit/new', 'SpecItemEditController@index');
Route::get('/spec-item-edit/{id}', 'SpecItemEditController@index');
Route::post('/spec-item-edit/search', 'SpecItemEditController@searchData');
Route::post('/spec-item-edit/save', 'SpecItemEditController@save');
Route::post('/spec-item-edit/delete', 'SpecItemEditController@delete');
// 在庫移管一覧
Route::get('/stock-transfer-list', 'StockTransferListController@index');
Route::post('/stock-transfer-list/search', 'StockTransferListController@searchData');
Route::post('/stock-transfer-list/delete', 'StockTransferListController@delete');
// 引当
Route::get('/stock-allocation', 'StockAllocationController@index');
Route::post('/stock-allocation/search', 'StockAllocationController@searchData');
Route::post('/stock-allocation/save', 'StockAllocationController@save');
Route::post('/stock-allocation/delete', 'StockAllocationController@delete');
// 在庫移管編集
Route::get('/stock-transfer-edit/new', 'StockTransferEditController@index');
Route::get('/stock-transfer-edit/{id}', 'StockTransferEditController@index');
Route::post('/stock-transfer-edit/search', 'StockTransferEditController@searchData');
Route::post('/stock-transfer-edit/save', 'StockTransferEditController@save');
Route::post('/stock-transfer-edit/delete', 'StockTransferEditController@delete');
// 在庫移管受入れ
Route::get('/stock-transfer-acceptance', 'StockTransferAcceptanceController@index');
Route::post('/stock-transfer-acceptance/search', 'StockTransferAcceptanceController@searchData');
Route::get('/stock-transfer-acceptance-shelf-qr', 'StockTransferAcceptanceShelfQrController@index');
Route::post('/stock-transfer-acceptance-shelf-qr/search', 'StockTransferAcceptanceShelfQrController@searchData');
Route::get('/stock-transfer-acceptance-check', 'StockTransferAcceptanceCheckController@index');
Route::post('/stock-transfer-acceptance-check/save', 'StockTransferAcceptanceCheckController@save');
// 在庫移管
Route::get('/stock-transfer', 'StockTransferController@index');
Route::post('/stock-transfer/search', 'StockTransferController@searchData');
Route::get('/stock-transfer-search', 'StockTransferSearchController@index');
Route::post('/stock-transfer-search/search', 'StockTransferSearchController@searchData');
Route::get('/stock-transfer-truck', 'StockTransferTruckController@index');
Route::post('/stock-transfer-truck/search', 'StockTransferTruckController@searchData');
Route::post('/stock-transfer-truck/save', 'StockTransferTruckController@save');
//倉庫内移動
Route::get('/shelf-move', 'ShelfMoveController@index');
Route::post('/shelf-move/search', 'ShelfMoveController@searchData');
Route::get('/shelf-move-scan-shelf', 'ShelfMoveScanShelfController@index');
Route::post('/shelf-move-scan-shelf/print', 'ShelfMoveScanShelfController@print');
Route::get('/shelf-move-scan-qr', 'ShelfMoveScanQrController@index');
Route::post('/shelf-move-scan-qr/search', 'ShelfMoveScanQrController@searchData');
Route::post('/shelf-move-scan-qr/search-shelf', 'ShelfMoveScanQrController@searchShelf');
Route::post('/shelf-move-scan-qr/save', 'ShelfMoveScanQrController@save');
//棚卸
Route::get('/inventory', 'InventoryController@index');
Route::post('/inventory/search', 'InventoryController@searchData');
Route::get('/inventory-product-list', 'InventoryProductListController@index');
Route::post('/inventory-product-list/save', 'InventoryProductListController@save');
Route::post('/inventory-product-list/print', 'InventoryProductListController@print');
Route::get('/inventory-product-addition', 'InventoryProductAdditionController@index');
Route::post('/inventory-product-addition/search', 'InventoryProductAdditionController@searchData');
Route::post('/inventory-product-addition/save', 'InventoryProductAdditionController@save');
Route::post('/inventory-product-addition/searchProduct', 'InventoryProductAdditionController@searchProduct');
// 棚番編集
// Route::get('/shelf-number-edit/new', 'ShelfNumberEditController@index');
Route::get('/shelf-number-edit/{id}', 'ShelfNumberEditController@index');
Route::post('/shelf-number-edit/save', 'ShelfNumberEditController@save');
Route::post('/shelf-number-edit/delete', 'ShelfNumberEditController@delete');
Route::post('/shelf-number-edit/export', 'ShelfNumberEditController@export');

// メーカー仕入先価格ファイルリンク
Route::get('/supplier-file-open/{supplier_id}', 'CommonController@openSupplierFile');

// 返品処理
Route::get('/return-process', 'ReturnProcessController@index');
Route::post('/return-process/search', 'ReturnProcessController@searchData');
Route::post('/return-process/approval', 'ReturnProcessController@approval');
Route::post('/return-process/rejection', 'ReturnProcessController@rejection');
Route::post('/return-process/process', 'ReturnProcessController@process');
Route::post('/return-process/cancel', 'ReturnProcessController@cancel');
Route::post('/return-process/print', 'ReturnProcessController@print');
// 返品受入れ
Route::get('/accepting-returns-input-select', 'AcceptingReturnsInputSelectController@index');
Route::get('/accepting-returns-matter-search', 'AcceptingReturnsMatterSearchController@index');
Route::post('/accepting-returns-matter-search/search', 'AcceptingReturnsMatterSearchController@searchData');
Route::get('/accepting-returns-delivery-list', 'AcceptingReturnsDeliveryListController@index');
Route::get('/accepting-returns-quantity-input', 'AcceptingReturnsQuantityInputController@index');
Route::post('/accepting-returns-quantity-input/save', 'AcceptingReturnsQuantityInputController@save');
Route::get('/accepting-returns-approval', 'AcceptingReturnsApprovalController@index');
Route::post('/accepting-returns-approval/search', 'AcceptingReturnsApprovalController@searchData');
Route::get('/accepting-returns-qr', 'AcceptingReturnsQrController@index');
Route::post('/accepting-returns-qr/search', 'AcceptingReturnsQrController@searchData');
Route::get('/accepting-returns-info-input', 'AcceptingReturnsInfoInputController@index');
Route::post('/accepting-returns-info-input/save', 'AcceptingReturnsInfoInputController@save');
Route::get('/accepting-returns-stock-search', 'AcceptingReturnsStockSearchController@index');
Route::post('/accepting-returns-stock-search/search', 'AcceptingReturnsStockSearchController@searchData');
// 廃棄
Route::get('/discard-list', 'DiscardListController@index');
Route::post('/discard-list/search', 'DiscardListController@searchData');
Route::get('/discard-confirmation', 'DiscardConfirmationController@index');
Route::post('/discard-confirmation/save', 'DiscardConfirmationController@save');
Route::get('/discard-sign', 'DiscardSignController@index');
// ﾒｰｶｰ引渡
Route::get('/maker-delivery', 'MakerDeliveryController@index');
Route::post('/maker-delivery/search', 'MakerDeliveryController@searchData');
Route::get('/maker-delivery-confirmation', 'MakerDeliveryConfirmationController@index');
Route::post('/maker-delivery-confirmation/save', 'MakerDeliveryConfirmationController@save');
Route::get('/maker-delivery-sign', 'MakerDeliverySignController@index');

// 共通名称マスタ一覧
Route::get('/general-list', 'GeneralListController@index');
Route::post('/general-list/search', 'GeneralListController@searchData');
// 共通名称マスタ編集
Route::get('/general-edit/{category_code}', 'GeneralEditController@index');
Route::post('/general-edit/save', 'GeneralEditController@save');
Route::post('/general-edit/delete', 'GeneralEditController@delete');

// 権限管理
Route::get('/authority-edit', 'AuthorityEditController@index');
Route::post('/authority-edit/save', 'AuthorityEditController@save');
Route::post('/authority-edit/search', 'AuthorityEditController@searchData');

// 倉庫別在庫管理
Route::get('/order-point-list', 'OrderPointListController@index');
Route::post('/order-point-list/search', 'OrderPointListController@searchData');
Route::post('/order-point-list/save', 'OrderPointListController@save');

// 売上一覧
Route::get('/sales-list', 'SalesListController@index');
Route::post('/sales-list/search', 'SalesListController@searchData');
Route::post('/sales-list/confirm-save', 'SalesListController@confirmSave');
Route::post('/sales-list/save', 'SalesListController@save');
Route::post('/sales-list/release', 'SalesListController@release');
Route::post('/sales-list/delete', 'SalesListController@delete');
Route::post('/sales-list/change-status', 'SalesListController@changeStatus');
Route::post('/sales-list/matter-complete', 'SalesListController@complete');


// 売上明細
Route::get('/sales-detail/{matter_id}', 'SalesDetailController@index');
Route::post('/sales-detail/save', 'SalesDetailController@save');
Route::post('/sales-detail/change-status', 'SalesDetailController@changeStatus');

// 請求一覧
Route::get('/request-list', 'RequestListController@index');
Route::post('/request-list/search', 'RequestListController@searchData');
Route::post('/request-list/confirm-print', 'RequestListController@confirmPrint');
Route::post('/request-list/print', 'RequestListController@print');
Route::post('/request-list/cancellation', 'RequestListController@cancellation');
Route::post('/request-list/closing', 'RequestListController@closing');
Route::post('/request-list/confirm-closing', 'RequestListController@confirmClosing');
Route::post('/request-list/closing-cancel', 'RequestListController@closingCancel');
Route::post('/request-list/output-sales-detail', 'RequestListController@outputSalesDetail');
Route::post('/request-list/upload-pdf', 'RequestListController@uploadPdf');
Route::post('/request-list/open-pdf', 'RequestListController@openPdf');
Route::post('/request-list/show-pdf', 'RequestListController@showPdf');
Route::post('/request-list/delete-request', 'RequestListController@deleteRequest');


// 店頭販売
Route::get('/counter-sale', 'CounterSaleController@index');
Route::post('/counter-sale/search', 'CounterSaleController@searchData');
Route::post('/counter-sale/getlist', 'CounterSaleController@getList');
Route::get('/counter-sale-confirm', 'CounterSaleConfirmController@index');
Route::get('/counter-sale-sign', 'CounterSaleSignController@index');
Route::post('/counter-sale-confirm/save', 'CounterSaleConfirmController@save');
Route::post('/counter-sale-confirm/print', 'CounterSaleConfirmController@print');

// テスト発注
Route::get('/test', 'TestController@index');
Route::post('/test/get-product-code-list', 'TestController@getProductCodeList');
Route::post('/test/get-product-name-list', 'TestController@getProductNameList');
Route::post('/test/confirm-matter', 'TestController@confirmMatter');

// 入金一覧
Route::get('/deposit-list', 'DepositListController@index');
Route::post('/deposit-list/search', 'DepositListController@searchData');
Route::post('/deposit-list/new-input', 'DepositListController@newInput');
Route::post('/deposit-list/comfirm-deposit', 'DepositListController@comfirmDeposit');
Route::post('/deposit-list/confirm-miscalculation', 'DepositListController@confirmMiscalculation');
Route::post('/deposit-list/miscalculation', 'DepositListController@miscalculation');
Route::post('/deposit-list/discount', 'DepositListController@discount');
Route::post('/deposit-list/discount-cancel', 'DepositListController@discountCancel');
Route::post('/deposit-list/delete', 'DepositListController@delete');
Route::post('/deposit-list/add', 'DepositListController@add');
Route::post('/deposit-list/back', 'DepositListController@back');
Route::post('/deposit-list/import-file', 'DepositListController@importFile');
Route::post('/deposit-list/complete-import', 'DepositListController@completeImport');

// カレンダー登録
Route::get('/calendar-data', 'CalendarDataController@index');
Route::post('/calendar-data/get-schedule-data', 'CalendarDataController@getScheduleData');
Route::post('/calendar-data/save', 'CalendarDataController@save');
Route::post('/calendar-data/delete', 'CalendarDataController@delete');
// カレンダーマスタ登録
Route::get('/calendar-edit', 'CalendarEditController@index');
Route::post('/calendar-edit/save', 'CalendarEditController@save');
Route::post('/calendar-edit/delete', 'CalendarEditController@delete');

// 中分類マスタ一覧
Route::get('/class-middle-list', 'ClassMiddleListController@index');
Route::post('/class-middle-list/search', 'ClassMiddleListController@searchData');
// 中分類マスタ編集
Route::get('/class-middle-edit/new', 'ClassMiddleEditController@index');
Route::get('/class-middle-edit/{id}', 'ClassMiddleEditController@index');
Route::post('/class-middle-edit/save', 'ClassMiddleEditController@save');
Route::post('/class-middle-edit/delete', 'ClassMiddleEditController@delete');

// 工程マスタ一覧
Route::get('/class-small-list', 'ClassSmallListController@index');
Route::post('/class-small-list/search', 'ClassSmallListController@searchData');
// 工程マスタ編集
Route::get('/class-small-edit/new', 'ClassSmallEditController@index');
Route::get('/class-small-edit/{id}', 'ClassSmallEditController@index');
Route::post('/class-small-edit/save', 'ClassSmallEditController@save');
Route::post('/class-small-edit/delete', 'ClassSmallEditController@delete');

// 木材立米単価入力
Route::get('/wood-unit-price-edit', 'WoodUnitPriceEditController@index');
Route::post('/wood-unit-price-edit/search', 'WoodUnitPriceEditController@searchData');
Route::post('/wood-unit-price-edit/save', 'WoodUnitPriceEditController@save');
Route::post('/wood-unit-price-edit/delete', 'WoodUnitPriceEditController@delete');

// 仕入倉庫受取納品
Route::get('/purchase-delivery-search', 'PurchaseDeliverySearchController@index');
Route::post('/purchase-delivery-search/search', 'PurchaseDeliverySearchController@searchData');
Route::get('/purchase-delivery-list', 'PurchaseDeliveryListController@index');
Route::post('/purchase-delivery-list/search', 'PurchaseDeliveryListController@searchData');
Route::get('/purchase-delivery-photo', 'PurchaseDeliveryPhotoController@index');
Route::get('/purchase-delivery-sign', 'PurchaseDeliverySignController@index');
Route::post('/purchase-delivery-sign/search', 'PurchaseDeliverySignController@searchData');
Route::post('/purchase-delivery-sign/save', 'PurchaseDeliverySignController@save');
Route::post('/purchase-delivery-sign/print', 'PurchaseDeliverySignController@print');

//引取
Route::get('/pickup-list', 'PickupListController@index');
Route::post('/pickup-list/search', 'PickupListController@searchData');
Route::get('/pickup-process', 'PickupProcessController@index');
Route::post('/pickup-process/search', 'PickupProcessController@searchData');
Route::get('/pickup-photo', 'PickupPhotoController@index');
Route::get('/pickup-sign', 'PickupSignController@index');
Route::post('/pickup-sign/save', 'PickupSignController@save');
Route::post('/pickup-sign/print', 'PickupSignController@print');


